USE callcenter;

ALTER TABLE contact_info 
MODIFY COLUMN id INT AUTO_INCREMENT;

ALTER TABLE customer
MODIFY COLUMN id INT AUTO_INCREMENT;

ALTER TABLE staff 
MODIFY COLUMN id INT AUTO_INCREMENT;

ALTER TABLE supervisor 
MODIFY COLUMN id INT AUTO_INCREMENT;

ALTER TABLE agent 
MODIFY COLUMN id INT AUTO_INCREMENT;

ALTER TABLE feedback 
MODIFY COLUMN id INT AUTO_INCREMENT;

ALTER TABLE issue 
MODIFY COLUMN id INT AUTO_INCREMENT;

ALTER TABLE `service` 
MODIFY COLUMN id INT AUTO_INCREMENT;

ALTER TABLE `call`
MODIFY COLUMN id INT AUTO_INCREMENT;